### ISSUE TITLE
wrong caching directory when XDG_CACHE_HOME not set

### ISSUE THREAD

**Issue by digitalhandwerker** [Gavinok/vim-troff#19]
Just wanted to report that I got an error after installing the plugin because nvim couldn't create the directory /home/username.cache
I think it's ment to be /home/username/.cache
After changing the file ftplugin/troff.vim to include the "/" everything worked fine for me.

I'm not yet very used to git so I am not able to make a pull request at the moment, but it should be an easy fix if I'm not mistaken:
**vim-troff/ftplugin/troff.vim**
```
@@ -62 +62 @@ if !exists('g:troff_ctags_file')
64 - 	let cahome = exists('$XDG_CACHE_HOME') ? $XDG_CACHE_HOME : usrhome.'.cache'
64 +	let cahome = exists('$XDG_CACHE_HOME') ? $XDG_CACHE_HOME : usrhome.'/.cache'
```
Hope this is of any use.

**Comment by Gavinok** [comment]
Should be fixed in my last commit. Let me know if it works for you.
